### PR TITLE
fix build with log4cxx 0.12

### LINKED ISSUE #1: Won't compile with latest log4cxx, please apply this patch
Hi,

There is this patch: https://github.com/ros/rosconsole/pull/51.patch to apply to make it compile with the latest version of log4cxx, could you add it to the PKGBUILD?

### PR DESCRIPTION
**Pull request by FederAndInk**
Fixes #1

### CODE REVIEW

**Comment by bionade24** [comment]
Thx!

**Comment by bionade24** [comment]
https://abs-cd.oscloud.info/cd_manager/ros-melodic-rosconsole

**Comment by FederAndInk** [comment]
@bionade24 if I understand correctly, this is the first step to build all ros-melodic-* with the latest log4cxx, I've seen the pkgbuilds from ros-noetic and it seems that you've changed some of them to compile with C++17 enabled:

```
> rg 'CMAKE_CXX_STANDARD|/17' ros-noetic-*/PKGBUILD
ros-noetic-urdf/PKGBUILD
52:    sed -i '25s/14/17/' ./${_dir}/CMakeLists.txt

ros-noetic-tf/PKGBUILD
68:        -DCMAKE_CXX_STANDARD=17

ros-noetic-stereo-image-proc/PKGBUILD
65:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-rviz/PKGBUILD
69:    sed -i '11s/14/17/' ./${_dir}/CMakeLists.txt

ros-noetic-rqt-image-view/PKGBUILD
59:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-robot-state-publisher/PKGBUILD
70:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-resource-retriever/PKGBUILD
56:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-position-controllers/PKGBUILD
52:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-pcl-ros/PKGBUILD
64:          -DCMAKE_CXX_STANDARD=17 \

ros-noetic-laser-filters/PKGBUILD
50:    sed -i '4s/11/17/' ${_dir}/CMakeLists.txt

ros-noetic-laser-geometry/PKGBUILD
49:    sed -i '4s/11/17/' ./${_dir}/CMakeLists.txt

ros-noetic-joint-state-controller/PKGBUILD
60:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-kdl-parser/PKGBUILD
40:    sed -i '5s/14/17/' ./${_dir}/CMakeLists.txt

ros-noetic-image-proc/PKGBUILD
63:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-gazebo-ros-control/PKGBUILD
59:        -DCMAKE_CXX_STANDARD=17

ros-noetic-gazebo-plugins/PKGBUILD
85:        -DCMAKE_CXX_STANDARD=17

ros-noetic-gazebo-ros/PKGBUILD
64:        -DCMAKE_CXX_STANDARD=17

ros-noetic-diff-drive-controller/PKGBUILD
61:        -DCMAKE_CXX_STANDARD=17 \

ros-noetic-depth-image-proc/PKGBUILD
68:        -DCMAKE_CXX_STANDARD=17 \
```

**Comment by bionade24** [comment]
This could also add some other caveats, so I'll try to avoid that if possible. When I have time, I'll look into that more closely. One consideration is to link against an older version of log4cxx.

**Comment by FederAndInk** [comment]
log4cxx support c++11, If `-DCMAKE_CXX_STANDARD=11` is specified when building, it will select boost for the missing parts, it may be another path to try.

**Pull request merged**
